// Navigation 
// Nests UL elements generated by nested-nav.xsl into their corresponding parent LI elements
// Words with production_root, root-relative, and absolute links
// Requires jQuery

// Last Updated 2/18/2014

$(function(){

	// if not using param-expose.xsl, replace with hardcoded values
	var $domain = OUC.globalProps['domain']
	var $currentPage = $domain + OUC.globalProps['path'] /* window.location */
	var $extension = OUC.globalProps['extension'] /* .html, .aspx, .php, etc */
	var $indexFile = OUC.globalProps['index-file'] /* default, index etc */
	
	// if the http root is not the same as domain
	var $trueHTTP = $domain

	// NEST NAVIGATION

	 $('ul[data-nav-path]').each(function(){ 
                                           
	   var $ul_parent_url = $(this).attr("data-nav-path")                                          
	   var $ul_node = $(this)
	   
	   
	   // Add "index.php (or equivalent) if link simply points to directory
	   if ($ul_parent_url.match(/\/$/))
		   $ul_parent_url += $indexFile + $extension
	   
	   $('ul[data-nav-path] > li > a').each(function(index, anchorTag){
	
		
	
	       $link = $(this).attr('href')
	       var $curr_url=$(this).parent("li").parents("ul").attr("data-nav-path");
		   
		   // Add "index.php (or equivalent) if link simply points to directory
		   if ($link.match(/\/$/))
			   $link += $indexFile + $extension	
		
	       // if the link goes to the default page of the navigation we're looking at
	       if( ($link  == $ul_parent_url || $trueHTTP+$ul_parent_url == $link)&&($curr_url!=$link) )
	       {
					   
	           //append the navigation under that link and mark the index page as bold (.currentPage)			
	           try{

	              	$(this).parent().append($ul_node)                                                      
	               	$(this).parent().addClass('selected')
	               
	               
	           } catch(e) {
	               //do nothing
	           }
	           
	           // break out of the loop
	           return false
	           
	       }				
	       
	   }); // end each link
	   
	  }); // end each list
    
    
    // FIND ACTIVE LINK 
    
    $('ul[data-nav-path] li a').each(function(index, anchorTag){
        
        $link =  $(this).attr('href')
           
        // check if link matches current page
        if ($currentPage == $link || $trueHTTP+$link == $currentPage)
        {
            $(this).addClass('active')
            
            // break out of the loop
            return false
            
        }
        
    });


	
}); // end function
